Position		Type			Value			Text

(1, 1)			KEYWORD			break				  break
(1, 9)			KEYWORD			case				  case
(1, 14)			KEYWORD			char				  char
(1, 19)			KEYWORD			const				  const
(1, 25)			KEYWORD			continue				  continue
(1, 34)			KEYWORD			default				  default
(1, 42)			KEYWORD			do				  do
(1, 45)			KEYWORD			double				  double
(1, 52)			KEYWORD			else				  else
(1, 57)			KEYWORD			enum				  enum
(3, 1)			KEYWORD			extern				  extern
(3, 8)			KEYWORD			float				  float
(3, 14)			KEYWORD			for				  for
(3, 18)			KEYWORD			goto				  goto
(3, 23)			KEYWORD			if				  if
(3, 26)			KEYWORD			int				  int
(3, 30)			KEYWORD			long				  long
(3, 35)			KEYWORD			register				  register
(3, 44)			KEYWORD			return				  return
(3, 51)			KEYWORD			short				  short
(5, 1)			KEYWORD			signed				  signed
(5, 8)			KEYWORD			sizeof				  sizeof
(5, 15)			KEYWORD			static				  static
(5, 22)			KEYWORD			struct				  struct
(5, 29)			KEYWORD			typedef				  typedef
(5, 37)			KEYWORD			union				  union
(5, 43)			KEYWORD			unsigned				  unsigned
(5, 52)			KEYWORD			void				  void
(5, 57)			KEYWORD			volatile				  volatile
(5, 66)			KEYWORD			while				  while
