Position		Type			Value			Text

(1, 1)			RELOP_EQ			==				  ==
(1, 4)			RELOP_GE			>=				  >=
(1, 7)			RELOP_LE			<=				  <=
(1, 10)			RELOP_LT			<				  <
(1, 12)			RELOP_GT			>				  >
(1, 14)			RELOP_NE			!=				  !=
(2, 1)			BITWISE_LSHIFT			<<				  <<
(2, 4)			BITWISE_RSHIFT			>>				  >>
(2, 7)			BITWISE_NOT			~				  ~
(2, 9)			BITWISE_XOR			^				  ^
(2, 11)			BITWISE_OR			|				  |
(2, 13)			BITWISE_AND			&				  &
(2, 15)			LOGIC_AND			&&				  &&
(2, 20)			LOBIC_OR			||				  ||
(2, 23)			LOGIC_NO			!				  !
(2, 25)			LSQUARE_BRACKET			[				  [
(2, 28)			RSQUARE_BRACKER			]				  ]
(2, 30)			LCURLY_BRACKET			{				  {
(2, 32)			RCURLY_BRACKET			}				  }
(2, 34)			LBRACKET			(				  (
(2, 39)			RBRACKET			)				  )
(2, 41)			PLUS			+				  +
(2, 45)			MINUS			-				  -
(2, 47)			DOUBLE_PLUS			++				  ++
(2, 50)			DOUBLE_MINUS			--				  --
(2, 53)			ASTERIX			*				  *
(2, 55)			FORWARD_SLASH			/				  /
(2, 57)			REMINDER			%				  %
(2, 59)			ARROW			->				  ->
(2, 64)			DOT			.				  .
(2, 66)			COMMA			,				  ,
(4, 1)			ASSIGNMENT_BY_SUM			+=				  +=
(4, 4)			ASSIGNMENT_BY_DIFFERENCE			-=				  -=
(4, 7)			ASSIGNMENT_BY_PRODUCT			*=				  *=
(4, 10)			ASSIGNMENT_BY_QUOTIENT			/=				  /=
(4, 13)			REMINDER			%				  %
(4, 14)			ASSIGNMENT			=				  =
(4, 16)			ASSIGNMENT_BY_BITWISE_LSHIFT			<<=				  <<=
(4, 20)			ASSIGNMENT_BY_BITWISE_RSHIFT			>>=				  >>=
(4, 24)			ASSIGNMENT_BY_BITWISE_XOR			^=				  ^=
(4, 27)			ASSIGNMENT_BY_BITWISE_OR			|=				  |=
(4, 30)			ASSIGNMENT_BY_BITWISE_XOR			^=				  ^=
(4, 33)			QUESTION_MARK			?				  ?
(4, 37)			COLON			:				  :
(4, 39)			ASSIGNMENT			=				  =
