Position		Type			Value			Text

(1, 1)			KEYWORD			void				  void
(1, 6)			ID			lc				  lc
(1, 8)			LBRACKET			(				  (
(1, 9)			KEYWORD			char				  char
(1, 14)			ASTERIX			*				  *
(1, 15)			ID			str				  str
(1, 18)			RBRACKET			)				  )
(3, 1)			LCURLY_BRACKET			{				  {
(5, 5)			KEYWORD			for				  for
(5, 8)			LBRACKET			(				  (
(5, 9)			KEYWORD			int				  int
(5, 13)			ID			i				  i
(5, 15)			ASSIGNMENT			=				  =
(5, 17)			NUM_INT			0				  0
(5, 18)			SEMICOLON			;				  ;
(5, 20)			ID			str				  str
(5, 23)			LSQUARE_BRACKET			[				  [
(5, 24)			ID			i				  i
(5, 25)			RSQUARE_BRACKER			]				  ]
(5, 27)			RELOP_NE			!=				  !=
(5, 30)			CHARACTER			39				  '\0'
(5, 34)			SEMICOLON			;				  ;
(5, 36)			DOUBLE_PLUS			++				  ++
(5, 38)			ID			i				  i
(5, 39)			RBRACKET			)				  )
(7, 5)			LCURLY_BRACKET			{				  {
(9, 9)			KEYWORD			if				  if
(9, 12)			LBRACKET			(				  (
(9, 13)			ID			str				  str
(9, 16)			LSQUARE_BRACKET			[				  [
(9, 17)			ID			i				  i
(9, 18)			RSQUARE_BRACKER			]				  ]
(9, 20)			RELOP_LE			<=				  <=
(9, 23)			CHARACTER			90				  'Z'
(9, 27)			LOGIC_AND			&&				  &&
(9, 30)			ID			str				  str
(9, 33)			LSQUARE_BRACKET			[				  [
(9, 34)			ID			i				  i
(9, 35)			RSQUARE_BRACKER			]				  ]
(9, 37)			RELOP_GE			>=				  >=
(9, 40)			CHARACTER			65				  'A'
(9, 43)			RBRACKET			)				  )
(11, 13)			ID			str				  str
(11, 16)			LSQUARE_BRACKET			[				  [
(11, 17)			ID			i				  i
(11, 18)			RSQUARE_BRACKER			]				  ]
(11, 20)			ASSIGNMENT_BY_SUM			+=				  +=
(11, 23)			NUM_INT			32				  32
(11, 25)			SEMICOLON			;				  ;
(13, 5)			RCURLY_BRACKET			}				  }
(15, 1)			RCURLY_BRACKET			}				  }
