└── Unit
    ├── Decl
    ├── Decl
    ├── Decl
    ├── Decl
    ├── Decl
    ├── Decl
    ├── Decl
    ├── Decl
    ├── Decl
    ├── Decl
    └── Decl
        └── InitDeclaratorList
            └── InitDeclarator
                ├── g
                ├── INT32
                └── Initializer 
                    └── 1

