//
// Created by keltar on 11/13/17.
//

#ifndef TINY_C_COMPILER_DECLARATION_SPECIFIERS_H
#define TINY_C_COMPILER_DECLARATION_SPECIFIERS_H

enum class DeclarationSpecifier
{
    VOID, CHAR, SHORT, INT, LONG, FLOAT, DOUBLE, SIGNED, UNSIGNED, STRUCT, ENUM,
    CONST,
};


#endif //TINY_C_COMPILER_DECLARATION_SPECIFIERS_H
